export default [
   ///BASIC///
   /* st */ {
      cat: 'basic',
      alias: 'st',
      syntax: 'git st',
      commands: ['git status'],
      title: 'status of repo',
      desc: '',
   },
   /* ad */ {
      cat: 'basic',
      alias: 'ad',
      syntax: 'git ad',
      commands: ['git add <file_name>'],
      title: 'add files to be staged',
      desc: '',
   },
   /* ct */ {
      cat: 'basic',
      alias: 'ct',
      syntax: "git ct '<message>'",
      commands: ["git commit -m '<message>'"],
      title: 'commit with message',
      desc: '',
   },
   ///COMMIT OPTIONS///
   /* dct */ {
      cat: 'commit',
      alias: 'dct',
      syntax: "git dct '<message>'",
      commands: ['git add .', "git commit -m '<message>'"],
      title: 'add + commit',
      desc: '',
   },
   /* ctp */ {
      cat: 'commit',
      alias: 'ctp',
      syntax: "git ctp '<message>'",
      commands: ["git commit -m '<message>'", 'git push'],
      title: 'commit + push',
      desc: '',
   },
   /* dctp */ {
      cat: 'commit',
      alias: 'dctp',
      syntax: "git dctp '<message>'",
      commands: ['git add .', "git commit -m '<message>'", 'git push'],
      title: 'add + commit + push',
      desc: '',
   },
   /* rct */ {
      cat: 'commit',
      alias: 'rct',
      syntax: "git rct '<message>'",
      commands: ['git add .', "git commit --amend --allow-empty -m '<message>'"],
      title: 'add + redo last commit',
      desc: '',
   },
   /* rctp */ {
      cat: 'commit',
      alias: 'rctp',
      syntax: "git rctp '<message>'",
      commands: [
         'git add .',
         "git commit --amend --allow-empty -m '<message>'",
         'git push --force',
      ],
      title: 'add + redo last commit + push',
      desc: '',
   },
   /* rcm */ {
      cat: 'commit',
      alias: 'rcm',
      syntax: "git rcm '<message>'",
      commands: ["git commit --amend --allow-empty -m '<message>'"],
      title: 'redo last commit message',
      desc: '',
   },
   /* rcmp */ {
      cat: 'commit',
      alias: 'rcmp',
      syntax: "git rcmp '<message>'",
      commands: ["git commit --amend --allow-empty -m '<message>'", 'git push --force'],
      title: 'redo last commit message + push',
      desc: '',
   },
   /* push-dist */ {
      cat: 'commit',
      alias: 'push-dist',
      syntax: 'git push-dist',
      commands: ['subtree push --prefix dist origin gh-pages'],
      title: 'push subfolder dist to gh-pages',
      desc: '',
   },
   /* push-gh-pages */ {
      cat: 'commit',
      alias: 'push-gh-pages',
      syntax: 'git push-gh-pages <folder>',
      commands: ['git subtree push --prefix <folder> origin gh-pages'],
      title: 'push any subfolder to gh-pages',
      desc: '',
   },
   ///FILE OPERATIONS///
   /* rename */ {
      cat: 'file',
      alias: 'rename',
      syntax: 'git rename <old-name> <new-name>',
      commands: ['git mv <old-name> <new-name>'],
      title: 'rename file',
      desc: '',
   },
   /* unstage */ {
      cat: 'file',
      alias: 'unstage',
      syntax: 'git unstage <file>',
      commands: ['git restore --staged <file>'],
      title: 'unstage file',
      desc: '',
   },
   /* unmodify */ {
      cat: 'file',
      alias: 'unmodify',
      syntax: 'git unmodify <file>',
      commands: ['git restore <file>'],
      title: 'unmodify file',
      desc: '',
   },
   /* untrack */ {
      cat: 'file',
      alias: 'untrack',
      syntax: 'git untrack <file>',
      commands: ['git rm --cached -r <file>'],
      title: 'untrack file',
      desc: '',
   },
   /* delete-untracked */ {
      cat: 'file',
      alias: 'delete-untracked',
      syntax: 'git delete-untracked',
      commands: ['git clean -d -f'],
      title: 'delete untracked files',
      desc: '',
   },
   ///BRANCH///
   /* branches */ {
      cat: 'branch',
      alias: 'branches',
      syntax: 'git branches',
      commands: ['git branch -a'],
      title: 'display all branches',
      desc: '',
   },
   /* sync */ {
      cat: 'branch',
      alias: 'sync',
      syntax: 'git sync',
      commands: ['git fetch -p --all', 'git pull'],
      title: 'sync local branch with remote',
      desc: '',
   },
   /* br */ {
      cat: 'branch',
      alias: 'br',
      syntax: 'git br <branch>',
      commands: ['git checkout -b <branch>'],
      title: 'create a branch & checkout',
      desc: '',
   },
   /* co */ {
      cat: 'branch',
      alias: 'co',
      syntax: 'git co <branch>',
      commands: ['git checkout <branch>'],
      title: 'checking out a branch',
      desc: '',
   },
   /* track */ {
      cat: 'branch',
      alias: 'track',
      syntax: 'git track <remote-branch>',
      commands: ['git push -u origin <remote-branch>'],
      title: 'set local branch to track remote branch',
      desc: '',
   },
   /* push-lb */ {
      cat: 'branch',
      alias: 'push-lb',
      syntax: 'git push-lb <local-branch>',
      commands: ['git push -u origin <local-branch>'],
      title: 'push local branch to remote',
      desc: '',
   },
   /* delete-lb */ {
      cat: 'branch',
      alias: 'delete-lb',
      syntax: 'git delete-lb <local-branch>',
      commands: ['git branch -d <local-branch>'],
      title: 'delete local branch',
      desc: '',
   },
   /* pull-rb */ {
      cat: 'branch',
      alias: 'pull-rb',
      syntax: 'git pull-rb <remote-branch>',
      commands: ['git fetch', 'git checkout <remote-branch>'],
      title: 'pull remote branch to local',
      desc: '',
   },
   /* delete-rb */ {
      cat: 'branch',
      alias: 'delete-rb',
      syntax: 'git delete-rb <remote-branch>',
      commands: ['git push --delete origin <remote-branch>'],
      title: 'delete remote branch',
      desc: '',
   },
   /* delete-lb-rb */ {
      cat: 'branch',
      alias: 'delete-lb-rb',
      syntax: 'git delete-lb-rb <branch>',
      commands: ['git branch -d <branch>', 'git push --delete origin <branch>'],
      title: 'delete local + remote branch',
      desc: '',
   },
   /* delete-rb-refs */ {
      cat: 'branch',
      alias: 'delete-rb-refs',
      syntax: 'git delete-rb-refs',
      commands: ['git fetch -p'],
      title: 'delete remote branch refs',
      desc: '',
   },
   //#TDR#//
   /* push-lb-tdr */ {
      cat: 'branch',
      alias: 'push-lb-tdr',
      syntax: 'git push-lb-tdr <remote> <local-branch>',
      commands: ['git push -u <remote> <local-branch>'],
      title: 'push local branch to different remote',
      desc: '',
   },
   /* delete-rb-tdr */ {
      cat: 'branch',
      alias: 'delete-rb-tdr',
      syntax: 'git delete-rb-tdr <remote> <remote-branch>',
      commands: ['git push --delete <remote> <remote-branch>'],
      title: 'delete remote branch of different remote',
      desc: '',
   },
   /* delete-lb-rb-tdr */ {
      cat: 'branch',
      alias: 'delete-lb-rb-tdr',
      syntax: 'git delete-lb-rb-tdr <remote> <branch>',
      commands: ['git branch -d <branch>', 'git push --delete <remote> <branch>'],
      title: 'delete local + remote branch of different remote',
      desc: '',
   },
   /* track-tdr */ {
      cat: 'branch',
      alias: 'track-tdr',
      syntax: 'git track-tdr <remote> <remote-branch>',
      commands: ['git push -u <remote> <remote-branch>'],
      title: 'set local branch to track remote branch of different remote',
      desc: '',
   },
   ///REMOTE///
   /* remote-details */ {
      cat: 'branch',
      alias: 'remote-details',
      syntax: 'git remote-details',
      commands: ['git remote show origin'],
      title: 'show the details of a remote',
      desc: '',
   },
   /* remote-url */ {
      cat: 'branch',
      alias: 'remote-url',
      syntax: 'git remote-url',
      commands: ['git remote -v'],
      title: '',
      desc: '',
   },
   /* add-remote */ {
      cat: 'branch',
      alias: 'add-remote',
      syntax: 'git add-remote <url>',
      commands: ['git remote add origin <url>'],
      title: 'add a remote',
      desc: '',
   },
   /* delete-remote */ {
      cat: 'branch',
      alias: 'delete-remote',
      syntax: 'git delete-remote',
      commands: ['git remote remove origin'],
      title: 'delete a remote',
      desc: '',
   },
   /* rename-remote */ {
      cat: 'branch',
      alias: 'rename-remote',
      syntax: 'git rename-remote <new-name>',
      commands: ['git remote rename origin <new-name>'],
      title: 'rename a remote',
      desc: '',
   },
   /* edit-remote-url */ {
      cat: 'branch',
      alias: 'edit-remote-url',
      syntax: 'git edit-remote-url <url>',
      commands: ['git remote remove origin', 'git remote add origin $1 <url>'],
      title: '',
      desc: '',
   },
   //#TDR#//
   /* remote-details-tdr */ {
      cat: 'branch',
      alias: 'remote-details-tdr',
      syntax: 'git remote-details-tdr <remote>',
      commands: ['git remote show <remote>'],
      title: 'show the details of a different remote',
      desc: '',
   },
   /* add-remote-tdr */ {
      cat: 'branch',
      alias: 'add-remote-tdr',
      syntax: 'git add-remote-tdr <remote> <url>',
      commands: ['git remote add <remote> <url>'],
      title: '',
      desc: '',
   },
   /* here */ {
      cat: 'branch',
      alias: '',
      syntax: 'git ',
      commands: ['git '],
      title: '',
      desc: '',
   },
   /* here */ {
      cat: 'branch',
      alias: '',
      syntax: 'git ',
      commands: ['git '],
      title: '',
      desc: '',
   },
   /* here */ {
      cat: 'branch',
      alias: '',
      syntax: 'git ',
      commands: ['git '],
      title: '',
      desc: '',
   },
   ///TAG///
   /* here */ {
      cat: 'branch',
      alias: '',
      syntax: 'git ',
      commands: ['git '],
      title: '',
      desc: '',
   },
];
